### ISSUE TITLE
Getting error running on Windows 64

### ISSUE THREAD

**Issue by maxEntropyProd** [Minres/mendel-sbml#1]
I just installed the 64 bit version of SBML-editor on a windows 64 box, but when executed the editor issues the error: "An error has occurred. See the log file null." Unfortunately, no log file is generated. I have Java JDK 18.0.1.1 installed.

**Comment by eyck** [comment]
Java 18 is not supported. The SBML Editor is in maintenance mode and needs Java 1.8.

**Comment by maxEntropyProd** [comment]
Thanks! i was just about to try that!
